name: TruffleRuby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  truffleruby:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby-head
        bundler-cache: true
    - name: Test installing the gem on TruffleRuby
      run: |
        bundle exec rake compile
        bundle exec rake build
        gem install pkg/debug-*.gem
